import assert from 'node:assert/strict';
import { adaptTelemetryReading } from '../../frontend/src/services/telemetryAdapter.js';
import { adaptReadingAnalytics, adaptLatestAnalytics } from '../../frontend/src/services/analyticsAdapter.js';
import { inspectRuntimeContract } from '../../frontend/src/services/runtimeContract.js';
import { conditionRating } from '../../frontend/src/domain/conditionRating.js';
let input = '';
for await (const chunk of process.stdin) input += chunk;
const bundle = JSON.parse(input);
const reading = adaptTelemetryReading(bundle.reading);
const analytics = adaptReadingAnalytics(bundle.analytics);
const latest = adaptLatestAnalytics(bundle.latest);
assert.equal(reading.readingId, analytics.reading_id);
assert.equal(latest.result.reading_id, reading.readingId);
assert.equal(analytics.metrics.find(metric => metric.path === 'electrical_metrics.capacity_loading_pct').status, 'available');
assert.equal(inspectRuntimeContract(bundle.spec).dataInputs, true);
const rating = conditionRating({latest: reading, analytics, details: bundle.asset}, 'live', Date.parse(reading.measurementTime)+1000);
assert.equal(rating.eligibleCount, 4);
assert.equal(rating.coverage, 100);
assert.ok(rating.breaches.some(factor => factor.id === 'oil'));
assert.equal(rating.factors.find(factor => factor.id === 'thermal').classification, 'normal');
console.log('Backend responses pass the actual frontend adapters and four-factor policy.');
