import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, ArrowRight, Check, ClipboardList, Database, Download, FileCheck2, FlaskConical, Radio, ShieldCheck, Thermometer, Wrench } from 'lucide-react';
import { Button } from '../ui/button.jsx';
import { Availability } from '../metrics/MetricPanel.jsx';
import { displayId, displayLocation, displayStatus, displaySource } from '../../lib/presentation.js';
import { number, time, readPreference, savePreference } from '../../lib/utils.js';
import { downloadReport } from '../../services/reportExport.js';
import { benchMeasurements, tripEvidence } from '../../data/workbookEvidence.js';
import { sampleSnapshot } from '../../data/workstationSample.js';
import { usableMeasurement } from '../../services/telemetryAdapter.js';
import { createTelemetryClient } from '../../services/telemetryClient.js';
import { boundedMap } from '../../services/storedStream.js';
import { allowedStatuses, isTerminal, statusLabels, updateRequest } from '../../services/maintenanceAdapter.js';
import BackendMaintenance from '../BackendMaintenance.jsx';

export function EmptyState({ icon: Icon = Database, title, children, action }) {
  return <div className="empty-state"><span><Icon size={28} strokeWidth={1.5} /></span><h3>{title}</h3><p>{children}</p>{action}</div>;
}
export function FleetView({ assets, mode, baseUrl, onSelect }) {
  const [records, setRecords] = useState({});
  const key = `${baseUrl}:${assets.map(asset => asset.asset_id).join(',')}`;
  useEffect(() => {
    if (mode !== 'live') return;
    const controller = new AbortController();
    const client = createTelemetryClient(baseUrl);
    boundedMap(assets, asset => client.getLatestTelemetry(asset.asset_id, 'device', null, controller.signal), controller.signal).then(results => {
      if (!controller.signal.aborted) setRecords({ key, values: Object.fromEntries(results.map((result, index) => [assets[index].asset_id, result])) });
    }).catch(() => { /* Cancellation is handled by the selection boundary. */ });
    return () => controller.abort();
  }, [assets, baseUrl, key, mode]);
  return <><div className="fleet-summary"><div><span>REGISTERED ASSETS ON THIS PAGE</span><strong>{assets.length.toString().padStart(2, '0')}</strong></div><p>Select a transformer to inspect its measurements and history.</p></div><div className="fleet-grid">{assets.map(asset => {
    const result = records.key === key ? records.values[asset.asset_id] : null;
    const reading = mode === 'sample' ? sampleSnapshot(asset.asset_id).latest : result?.value;
    return <button className="card fleet-asset" key={displayId(asset.asset_id)} onClick={() => onSelect(asset.asset_id)}><div className="fleet-asset-top"><span className="asset-symbol"><Radio size={22} /></span><Availability state={mode === 'sample' ? 'Sample' : reading ? 'Stored' : result?.error?.status === 404 ? 'Unavailable' : 'Unknown'} /></div><h2>{asset.name}</h2><p>{displayLocation(asset.location)}</p><span className="mono">{displayId(asset.asset_id)}</span><dl><div><dt>Rated capacity</dt><dd>{number(asset.current_configuration?.rated_kva, 0)} kVA</dd></div><div><dt>Oil temperature</dt><dd>{number(usableMeasurement(reading, 'oil_temperature_c'))} °C</dd></div><div><dt>Measured</dt><dd>{time(reading?.measurementTime, true)}</dd></div><div><dt>Processing</dt><dd>{displayStatus(reading?.processingJobStatus ?? result?.error?.message)}</dd></div></dl><div className="fleet-asset-link">Open digital twin<ArrowRight size={16} /></div></button>;
  })}</div></>;
}

export function QualityView({ snapshot }) {
  const reading = snapshot?.latest;
  const analytics = snapshot?.analytics;
  const completed = snapshot?.completedAnalytics;
  const config = snapshot?.details?.current_configuration;
  const latency = reading?.arrivalTime && reading?.measurementTime ? (Date.parse(reading.arrivalTime) - Date.parse(reading.measurementTime)) / 1000 : null;
  return <div className="quality-grid"><section className="card"><div className="panel-head"><h2>Reading provenance</h2><Database size={17} /></div><dl className="metadata-list"><div><dt>Asset / reading</dt><dd>{displayId(reading?.assetId)} / {displayId(reading?.readingId, 'none')}</dd></div><div><dt>Measurement time (UTC)</dt><dd>{reading?.measurementTime ?? 'Unavailable'}</dd></div><div><dt>Arrival time (UTC)</dt><dd>{reading?.arrivalTime ?? 'Unavailable'}</dd></div><div><dt>Telemetry latency</dt><dd>{number(latency, 2)} s</dd></div>{reading?.runId !== 'ui-illustration' && <div><dt>Source / run</dt><dd>{displaySource(reading?.source)} / {reading?.runId ?? 'none'}</dd></div>}<div><dt>Configuration version</dt><dd>{reading?.configurationVersion ?? 'Unavailable'}</dd></div><div><dt>Out of order</dt><dd>{reading?.outOfOrder == null ? 'Unknown' : reading.outOfOrder ? 'Yes' : 'No'}</dd></div></dl><p className="subtle-note">Sensor response time is unavailable. Measurement time, arrival time and processing time describe different stages.</p></section>
    <section className="card"><div className="panel-head"><h2>Analytics processing</h2><ShieldCheck size={17} /></div><dl className="metadata-list"><div><dt>Latest telemetry job</dt><dd>{displayStatus(analytics?.status ?? reading?.processingJobStatus)}</dd></div><div><dt>Latest completed reading</dt><dd>{completed?.reading_id ?? 'None retrieved'}</dd></div><div><dt>Completed measurement time</dt><dd>{completed?.measurement_time ?? 'Unavailable'}</dd></div><div><dt>Model identity</dt><dd>{analytics?.result?.model_id ?? 'Unavailable'}</dd></div><div><dt>Model version</dt><dd>{analytics?.result?.model_version ?? 'Unavailable'}</dd></div><div><dt>Parameter version</dt><dd>{analytics?.result?.parameter_version ?? 'Unavailable'}</dd></div><div><dt>Result stored (UTC)</dt><dd>{analytics?.result?.created_at ?? 'Unavailable'}</dd></div></dl>{snapshot?.latestEnvelope?.lagging && <div className="inline-notice warning">The newest reading and latest completed result are different. Estimates shown with the newest reading remain unavailable until its result is returned.</div>}{completed?.result && <details className="completed-result"><summary>Latest completed result · reading {completed.reading_id}</summary><dl className="metadata-list"><div><dt>Model</dt><dd>{completed.result.model_id}</dd></div><div><dt>Version</dt><dd>{completed.result.model_version}</dd></div><div><dt>Parameters</dt><dd>{completed.result.parameter_version}</dd></div><div><dt>Stored at (UTC)</dt><dd>{completed.result.created_at}</dd></div><div><dt>Configuration</dt><dd>{completed.configuration_version}</dd></div></dl><p className="subtle-note">This result belongs to reading {completed.reading_id}. It is not substituted into the newest telemetry.</p></details>}</section>
    <section className="card"><div className="panel-head"><h2>Channel quality</h2><Radio size={17} /></div>{reading ? Object.entries(reading.measurements).map(([name, value]) => <div className="quality-row" key={name}><span>{name.replaceAll('_', ' ')}</span><span className={`quality-flag ${reading.measurementQuality?.[name] === 'good' ? 'quality-good' : ''}`}>{reading.measurementQuality?.[name] ?? 'unknown'}</span><small>{reading.qualityFlags?.[name]?.join(', ') || (value == null ? 'missing' : 'No flags returned')}</small></div>) : <p>No reading available.</p>}<p className="subtle-note">Channel quality describes input usability. It does not establish transformer health.</p></section>
    <section className="card"><div className="panel-head"><h2>Configuration & assumptions</h2><ClipboardList size={17} /></div><dl className="metadata-list"><div><dt>Version</dt><dd>{config?.version ?? 'Unavailable'}</dd></div><div><dt>Measurement side</dt><dd>{config?.measurement_side ?? 'Unavailable'}</dd></div><div><dt>Voltage basis</dt><dd>{config?.voltage_convention?.replaceAll('_', ' ') ?? 'Unavailable'}</dd></div><div><dt>Cooling type</dt><dd>{config?.cooling_type ?? 'Unavailable'}</dd></div></dl><details><summary>Parameter provenance</summary>{Object.entries(config?.parameter_provenance ?? {}).map(([name, value]) => <div className="provenance-row" key={name}><span>{name}</span><strong>{value}</strong></div>)}</details>{config?.asset_id !== reading?.assetId || config?.version !== reading?.configurationVersion ? <p className="subtle-note">The registry's current configuration may differ from the reading's configuration. Model outputs retain their own configuration identity.</p> : null}</section>
  </div>;
}

export function LimitChecks({ snapshot, mode }) {
  const observations = snapshot?.analytics?.result?.payload?.anomaly_observations;
  let checks = Array.isArray(observations) ? observations.filter(item => item.kind === 'configured_limit_check').map(item => ({ ...item, status: item.status === 'available' && Number.isFinite(item.value) && Number.isFinite(item.threshold) && typeof item.breached === 'boolean' && ['gt', 'lt'].includes(item.relation) && typeof item.quantity === 'string' ? 'available' : 'unavailable', quantity: typeof item.quantity === 'string' ? item.quantity : 'Unknown quantity' })) : [];
  if (mode === 'sample' && snapshot) {
    const config = snapshot.details.current_configuration;
    checks = [
      { quantity: 'Oil temperature', value: snapshot.latest.measurements.oil_temperature_c, threshold: config.operational_limits.max_top_oil_temp_c, unit: '°C' },
      { quantity: 'Capacity loading', value: snapshot.analytics.metrics.find(item => item.path.endsWith('capacity_loading_pct'))?.value, threshold: config.operational_limits.max_load_pct, unit: '%' },
    ].map(check => ({ ...check, status: Number.isFinite(check.value) ? 'available' : 'unavailable', relation: 'gt', breached: Number.isFinite(check.value) ? check.value > check.threshold : null, interpretation: 'Compared with the configured threshold.' }));
  }
  return <section className="card"><div className="panel-head"><h2>Configured-limit checks</h2><span className="tiny-tag">Reading {displayId(snapshot?.latest?.readingId, 'unavailable')}</span></div><p className="subtle-note">These instant comparisons retain the source reading and configured threshold. Incident lifecycle and acknowledgement require the future registry.</p>{checks.length ? <div className="checks-list">{checks.map((check, index) => <article className="limit-check" key={index}><span className={`check-symbol ${check.status !== 'available' ? 'unknown' : check.breached ? 'breach' : ''}`}>{check.status !== 'available' ? '?' : check.breached ? <AlertTriangle size={16} /> : <Check size={16} />}</span><div><strong>{check.quantity.replaceAll('_', ' ')}</strong><p>{check.status !== 'available' ? 'Unavailable evidence' : `${number(check.value, 2)} ${check.unit === 'C' ? '°C' : check.unit} · ${check.relation === 'lt' ? 'minimum' : 'maximum'} ${number(check.threshold, 2)} ${check.unit === 'C' ? '°C' : check.unit}`}</p><small>{check.interpretation}</small></div><span className="check-status">{check.status !== 'available' ? 'Not assessed' : check.breached ? 'Limit breached' : 'Within this limit'}</span></article>)}</div> : <EmptyState icon={AlertTriangle} title="No configured-limit evidence retrieved">The selected reading has no stored limit checks. Missing evidence does not indicate normal operation.</EmptyState>}<p className="subtle-note">Measured: {time(snapshot?.latest?.measurementTime, true)} · Configuration {snapshot?.latest?.configurationVersion ?? 'unavailable'}</p></section>;
}
export function IncidentsView({ snapshot, mode }) {
  return <><LimitChecks snapshot={snapshot} mode={mode} /><section className="card"><EmptyState icon={AlertTriangle} title="Incident registry is not integrated">Persistent incidents, evidence timelines and authenticated acknowledgement need an integrated backend contract. The current interface shows reading-bound limit checks above.</EmptyState></section></>;
}

export function WhatIfView({ snapshot }) {
  const [loading, setLoading] = useState(100);
  const [ambient, setAmbient] = useState(30);
  const [duration, setDuration] = useState(60);
  return <div className="whatif-grid"><section className="card"><div className="panel-head"><h2>Scenario inputs</h2><Availability state="Planned" /></div><div className="scenario-preset"><FlaskConical size={17} /><div><strong>120% loading scenario</strong><small>A hypothetical input, with no assessed permissible duration.</small></div><Button variant="outline" size="sm" onClick={() => setLoading(120)}>Use preset</Button></div><label>Capacity loading <span>{loading}%</span><input aria-label="Scenario loading" type="range" min="20" max="150" value={loading} onChange={event => setLoading(Number(event.target.value))} /></label><label>Ambient temperature (°C)<input type="number" min="-30" max="60" value={ambient} onChange={event => setAmbient(event.target.value)} /></label><label>Duration (minutes)<input type="number" min="1" max="1440" value={duration} onChange={event => setDuration(event.target.value)} /></label><dl className="metadata-list"><div><dt>Baseline reading</dt><dd>{displayId(snapshot?.latest?.readingId)}</dd></div><div><dt>Rated capacity</dt><dd>{number(snapshot?.details?.current_configuration?.rated_kva, 0)} kVA</dd></div><div><dt>Cooling assumption</dt><dd>{snapshot?.details?.current_configuration?.cooling_type ?? 'Unavailable'}</dd></div></dl><Button disabled><FlaskConical size={15} />Comparison API unavailable</Button></section><section className="card"><EmptyState icon={FlaskConical} title="Comparison is not assessed">No persisted What-if endpoint is integrated. Forecasts, temperature deltas, overload duration and field advice will appear here when a validated model returns them.</EmptyState><div className="whatif-assumptions"><h3>Required for a valid comparison</h3><p>Reading and configuration identity, validated thermal parameters, ambient conditions, duration, cooling assumptions, model version and an explicit hypothetical-state boundary.</p></div></section></div>;
}

function loadSampleTasks(assetId) {
  try { const tasks = JSON.parse(readPreference(`powernxt-sample-tasks:${assetId}`, '[]')); return Array.isArray(tasks) ? tasks.filter(task => task.assetId === assetId && statusLabels[task.status] && Number.isInteger(task.version)) : []; } catch { return []; }
}
function SampleTask({ task, onSave }) {
  const [draft, setDraft] = useState({ owner: task.owner, status: task.status, notes: task.notes });
  const [error, setError] = useState('');
  const terminal = isTerminal(task.status);
  return <article className="sample-task"><div className="panel-head"><h3>{task.title}</h3><span className="tiny-tag">{statusLabels[task.status]} · v{task.version}</span></div><p className="subtle-note">Task {displayId(task.id)}</p><form onSubmit={event => {
    event.preventDefault();
    try { const patch = updateRequest(task, draft); onSave({ ...task, ...draft, version: patch.expected_version + 1 }); setError(''); } catch (failure) { setError(failure.message); }
  }}><label>Assigned person<input maxLength={100} disabled={terminal} value={draft.owner} onChange={event => setDraft({ ...draft, owner: event.target.value })} /></label><label>Task status<select disabled={terminal} value={draft.status} onChange={event => setDraft({ ...draft, status: event.target.value })}>{(terminal ? [task.status] : allowedStatuses(task.status)).map(status => <option value={status} key={status}>{statusLabels[status]}</option>)}</select></label><label>Notes<textarea disabled={terminal} maxLength={2000} value={draft.notes} onChange={event => setDraft({ ...draft, notes: event.target.value })} /></label>{error && <p role="alert" className="error">{error}</p>}<Button type="submit" disabled={terminal}>Save update</Button></form></article>;
}
export function MaintenanceView({ mode, baseUrl, assetId, onAssetChange, contractEnabled = false }) {
  const [tasks, setTasks] = useState(() => loadSampleTasks(assetId));
  const [title, setTitle] = useState('');
  const [owner, setOwner] = useState('');
  const [notice, setNotice] = useState('');
  const sequence = useRef(0);
  if (mode === 'live' && !contractEnabled) return <section className="card"><EmptyState icon={Wrench} title="Maintenance contract not enabled">The connected runtime does not advertise an implemented maintenance route family. No task request is made. Genuine incident-linked tasks require persisted evidence and authenticated, versioned actions.</EmptyState><div className="planned-comparison"><div><span>Task queue</span><strong>No records retrieved</strong></div><div><span>Selected task evidence</span><strong>Contract required</strong></div></div></section>;
  if (mode === 'live') return <div className="legacy-workflow"><BackendMaintenance baseUrl={baseUrl} selectedAssetId={assetId} onAssetChange={onAssetChange} /></div>;
  function save(next) { setTasks(next); savePreference(`powernxt-sample-tasks:${assetId}`, JSON.stringify(next)); }
  return <div className="maintenance-grid"><section className="card"><div className="panel-head"><h2>Create task</h2><Wrench size={17} /></div><div className="inline-notice">Tasks are saved in this browser.</div><form onSubmit={event => {
    event.preventDefault();
    const task = { id: `sample-task-${Date.now()}-${++sequence.current}`, assetId, title: title.trim(), owner: owner.trim(), status: 'open', notes: '', version: 1 };
    save([...tasks, task]); setTitle(''); setNotice('Task saved.');
  }}><label>Task action<input required maxLength={1000} placeholder="Describe the inspection" value={title} onChange={event => setTitle(event.target.value)} /></label><label>Assigned person<input maxLength={100} placeholder="Optional display name" value={owner} onChange={event => setOwner(event.target.value)} /></label><Button type="submit" disabled={!title.trim()}><Wrench size={15} />Create task</Button></form>{notice && <p role="status" className="success">{notice}</p>}</section><section className="card"><div className="panel-head"><h2>Tasks</h2><span className="tiny-tag">{tasks.length} saved</span></div>{tasks.length ? tasks.map(task => <SampleTask key={task.id} task={task} onSave={updated => { save(tasks.map(item => item.id === updated.id ? updated : item)); setNotice('Task updated.'); }} />) : <EmptyState icon={ClipboardList} title="No tasks yet">Create an inspection or maintenance task.</EmptyState>}</section></div>;
}

export function ReportsView({ snapshot, mode, onExport }) {
  const [tab, setTab] = useState('records');
  return <><div className="view-tabs"><button aria-pressed={tab === 'records'} onClick={() => setTab('records')}>Telemetry report</button><button aria-pressed={tab === 'bench'} onClick={() => setTab('bench')}>Bench validation reference</button></div>{tab === 'records' ? <section className="card"><div className="panel-head"><h2>Asset telemetry report</h2><Button disabled={!snapshot?.history?.length} onClick={() => { downloadReport(snapshot, mode); onExport(); }}><Download size={15} />Export CSV</Button></div><div className="report-scope"><FileCheck2 size={24} /><div><strong>Telemetry records</strong><p>{snapshot?.history?.length ?? 0} records · {displayId(snapshot?.details?.asset_id, 'No asset')} · history page {Math.floor((snapshot?.page?.offset ?? 0) / 20) + 1}</p></div></div><dl className="metadata-list">{mode !== 'sample' && <div><dt>Source / run</dt><dd>{displaySource(snapshot?.latest?.source)} / {snapshot?.latest?.runId ?? 'none'}</dd></div>}<div><dt>First retrieved time (UTC)</dt><dd>{snapshot?.history?.[0]?.measurementTime ?? 'Unavailable'}</dd></div><div><dt>Last retrieved time (UTC)</dt><dd>{snapshot?.history?.at(-1)?.measurementTime ?? 'Unavailable'}</dd></div></dl><p className="subtle-note">CSV includes units in channel names, UTC measurement and arrival times, reading/configuration identity, quality flags, processing state, available thermal estimates and model provenance. Only this fetched page is exported. Load other pages to export them separately.</p><div className="table-wrap"><table><caption>Measurements</caption><thead><tr><th>Reading</th><th>Measurement time (IST)</th><th>Oil (°C)</th><th>Ambient (°C)</th><th>Oil level (%)</th><th>Processing</th></tr></thead><tbody>{snapshot?.history?.map(reading => <tr key={reading.readingId}><td>{displayId(reading.readingId)}</td><td>{time(reading.measurementTime, true)}</td><td>{number(reading.measurements.oil_temperature_c)}</td><td>{number(reading.measurements.ambient_temperature_c)}</td><td>{number(reading.measurements.oil_level_pct)}</td><td>{displayStatus(reading.processingJobStatus)}</td></tr>)}</tbody></table></div></section> : <BenchReference />}</>;
}
function BenchReference() {
  return <section className="card"><div className="panel-head"><h2>Condition-monitoring bench tests</h2><Availability state="Sample" /></div><p className="subtle-note">Draft Data for Condition Monitoring.xlsx · Sheet1, A1:H35. Reference and software observations have no asset identity or measurement timestamps. This table is separate from telemetry.</p><div className="table-wrap"><table><caption>Workbook rows 4–10 · difference = reference − software; percentage = difference ÷ reference × 100; acceptance = |percentage| ≤ 1</caption><thead><tr><th>Measurement</th><th>Reference</th><th>Software</th><th>Difference</th><th>Difference (%)</th><th>Within 1%</th></tr></thead><tbody>{benchMeasurements.map(item => <tr key={item.row}><td>{item.label} ({item.unit})</td><td>{number(item.reference, 2)}</td><td>{number(item.software, 2)}</td><td>{number(item.difference, 2)}</td><td>{number(item.percent, 3)}</td><td>{item.withinTolerance ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div><h3>Current-trip observations</h3><p className="subtle-note">Workbook rows 16–19: “Tripped by set current of 50 A.” Differences in this section use software − reference. No trip timing values are supplied.</p><div className="bench-tests">{tripEvidence.current.map(item => <div key={item.phase}><span>{item.phase} phase</span><strong>{number(item.reference, 2)} → {number(item.software, 2)} A</strong><small>Difference {number(item.software - item.reference, 2)} A</small></div>)}</div><h3>Temperature-trip observations</h3><p className="subtle-note">Workbook rows 23–25: setting 60 °C. Differences use software − reference.</p><div className="bench-tests">{tripEvidence.temperature.map((item, index) => <div key={index}><span>Observation {index + 1}</span><strong>{number(item.reference, 2)} → {number(item.software, 2)} °C</strong><small>Difference {number(item.software - item.reference, 2)} °C</small></div>)}</div><div className="inline-notice"><Thermometer size={16} />The oil-leak section requires a sensor and has no recorded oil series. GPRS/master-number and AI notes are requirements only.</div></section>;
}
