import { useState } from 'react';
import { ArrowRight, Droplets, Gauge, Layers3, ShieldCheck, Thermometer, Zap, Wrench } from 'lucide-react';
import { Availability, MetricRow } from '../metrics/MetricPanel.jsx';
import { Button } from '../ui/button.jsx';
import { anchors } from '../../data/capabilities.js';
import { usableMeasurement } from '../../services/telemetryAdapter.js';
import { displayId } from '../../lib/presentation.js';
import { number, time } from '../../lib/utils.js';

const groups = [
  { id: 'power', name: 'Power & electrical', icon: Zap, purpose: 'Phase measurements and supported power quantities, with a clear separation between meter channels and model outputs.', ids: ['voltage_r_v','voltage_y_v','voltage_b_v','current_r_a','current_y_a','current_b_a','apparent_power','capacity_loading','phase_loading','current_imbalance','voltage_imbalance','active_power','reactive_power','power_factor','frequency','thd'], slots: ['Meter/measurement convention', 'Phase-angle or power channel', 'Harmonic definition and sampling window'], contract: 'Power meter channels, explicit aggregation and units; compatible completed analytics for derived quantities.' },
  { id: 'oil', name: 'Oil system', icon: Droplets, purpose: 'Inspect measured level and oil temperature. Direct leakage evidence remains separate from a low-level observation.', ids: ['oil_level_pct','oil_temperature_c','oil_leak'], slots: ['Direct leak signal: unavailable', 'Verified leakage events: not retrieved', 'Sensor/inspection identity: unavailable'], contract: 'Dedicated leak contact or inspection event with timestamp, quality, source and reviewed event semantics.' },
  { id: 'pressure', name: 'Pressure & sensors', icon: Gauge, purpose: 'Pressure instrument inventory and specifications. A timestamp delay is never a sensor response specification.', ids: ['pressure','response_time','telemetry_latency','processing_duration'], slots: ['Sensor ID and mounting location', 'Gauge/absolute pressure basis', 'Range, response specification, sampling and calibration'], contract: 'Pressure telemetry and instrument metadata; independent worker start/end timing for processing duration.' },
  { id: 'thermal', name: 'Thermal & capacity', icon: Thermometer, purpose: 'Measured and estimated oil behavior alongside future duration-dependent overload and winding assessments.', ids: ['rated_capacity','thermal_load','oil_temperature_c','ambient_temperature_c','estimated_oil','thermal_residual','thermal_capacity','overload_duration','winding','hotspot','bushing','whatif_result'], slots: ['Initial thermal state and cooling', 'Ambient and load-vs-duration basis', 'Permitted duration: not assessed'], contract: 'Validated overload/hot-spot methodology, approved limits, cooling/ambient assumptions and model provenance.' },
  { id: 'fault', name: 'Impedance & fault level', icon: Layers3, purpose: 'Keep prospective short-circuit capacity distinct from a detected fault event and ordinary high-current readings.', ids: ['impedance','short_circuit'], slots: ['Nameplate impedance %: unavailable', 'Rated voltage/kVA basis', 'Source/network impedance: unavailable'], contract: 'Verified impedance and network boundary, approved formula/version and unit-validated prospective kA/MVA result.' },
  { id: 'mechanical', name: 'Electrical ↔ mechanical', icon: Layers3, purpose: 'A future aligned-signal comparison. No vibration, relationship coefficient or mechanical diagnosis is inferred.', ids: ['vibration','correlation'], slots: ['Electrical evidence: current stream only', 'Mechanical signal: not instrumented', 'Aligned comparison: unavailable'], contract: 'Synchronized mechanical channels, axis/location/unit, sampling bandwidth, alignment method and validated interpretation.' },
  { id: 'life', name: 'Health, ageing & life', icon: ShieldCheck, purpose: 'Inspect health, ageing and service-life measurements.', ids: ['health','fault','ageing','lifespan','rul'], slots: ['Assessed horizon: unavailable', 'Method and calibration: unavailable', 'Uncertainty: not estimated'], contract: 'Validated health/ageing/RUL output with inputs, period, scale, uncertainty, model and configuration binding.' },
  { id: 'actions', name: 'Maintenance & incidents', icon: Wrench, purpose: 'Evidence-linked action patterns for a future authenticated incident and recommendation workflow.', ids: ['maintenance_recommendation','incident_lifecycle'], slots: ['Triggering incident: unavailable', 'Recommendation rationale: not assessed', 'Authorized action/history: unavailable'], contract: 'Persisted incident/evidence IDs, approved maintenance rules, authenticated actor, allowed transitions and version history.' },
];
export default function CapabilityExplorer({ metrics, selected, onSelect, snapshot, onTrend }) {
  const [groupId, setGroupId] = useState('oil');
  const group = groups.find(item => item.id === groupId);
  const Icon = group.icon;
  return <div className="capability-explorer"><nav className="capability-nav" aria-label="Condition capability groups">{groups.map(item => <button key={item.id} aria-pressed={groupId === item.id} onClick={() => setGroupId(item.id)}><item.icon size={18} /><span>{item.name}</span><ArrowRight size={14} /></button>)}</nav><section key={groupId} className="card capability-record"><div className="capability-intro"><span className="component-icon"><Icon size={23} /></span><div><span className="eyebrow">CONDITION EXPLORER</span><h2>{group.name}</h2><p>{group.purpose}</p></div></div><div className="capability-values">{group.ids.map(id => { const metric = metrics.find(item => item.id === id); return metric && <div key={id}><MetricRow metric={metric} selected={selected?.id === id} onSelect={next => onSelect(next, true)} />{metric.type === 'future' && <p><Availability state={metric.state} />{metric.reason}</p>}</div>; })}</div>
    <div className="capability-evidence"><h3>Evidence and contract readiness</h3><dl className="metadata-list"><div><dt>Selected record</dt><dd>{displayId(snapshot?.latest?.readingId, 'None retrieved')}</dd></div><div><dt>Measurement time</dt><dd>{time(snapshot?.latest?.measurementTime, true)} IST</dd></div><div><dt>Region</dt><dd>{anchors[metrics.find(metric => metric.id === group.ids[0])?.anchor]?.label ?? 'Asset-level'} · sensor position unverified</dd></div></dl><ul>{group.slots.map(slot => <li key={slot}>{slot}</li>)}</ul><p><strong>PROPOSED — NOT LIVE</strong><br />{group.contract}</p><a href={new URL('../../../docs/future-capability-contracts.md', import.meta.url).href} target="_blank" rel="noreferrer">Read the future contract note<ArrowRight size={14} /></a>{group.id === 'oil' && <Button variant="outline" onClick={() => onTrend('oil_level')}>Inspect available oil-level history</Button>}</div>
    {group.id === 'pressure' && <SensorInventory snapshot={snapshot} />}
    {group.id === 'mechanical' && <div className="planned-comparison"><div><span>Electrical signal</span><strong>Reading {displayId(snapshot?.latest?.readingId, 'unavailable')}</strong></div><span>↔</span><div><span>Mechanical signal</span><strong>Not instrumented</strong></div><p>No compatible synchronized mechanical records. Comparison is not assessed.</p></div>}
    {group.id === 'actions' && <div className="planned-recommendation"><Wrench size={20} /><div><strong>No supported predictive-maintenance recommendation</strong><p>Trigger, urgency, rationale, method and incident-linked action will be supplied by a reviewed backend contract. No maintenance schedule is inferred.</p></div></div>}
  </section></div>;
}
export function SensorInventory({ snapshot }) {
  return <section className="sensor-inventory"><h3>Instrument inventory · metadata unavailable</h3><p>Measurement channels do not establish installed sensor identity. No inventory API is implemented in this workspace.</p><div className="table-wrap"><table><caption>Requested instrument capabilities · no assumed installations</caption><thead><tr><th>Quantity</th><th>Reading</th><th>Instrument / location</th><th>Range / response / calibration</th></tr></thead><tbody><tr><td>Oil temperature (°C)</td><td>{number(usableMeasurement(snapshot?.latest, 'oil_temperature_c'))}</td><td>Identity and mounting unknown</td><td>Not provided</td></tr><tr><td>Tank pressure (kPa)</td><td>Not instrumented</td><td>No inventory evidence</td><td>Not provided</td></tr><tr><td>Direct leakage signal</td><td>Not instrumented</td><td>No inventory evidence</td><td>Not provided</td></tr></tbody></table></div></section>;
}
