"""add durable analytics worker

Revision ID: d730a91b4c22
Revises: ce21c3b8140a
Create Date: 2026-10-09 09:17:19.629386+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d730a91b4c22"
down_revision: str | None = "ce21c3b8140a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_results",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("reading_id", sa.BigInteger(), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("parameter_version", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'unavailable')", name="ck_analytics_result_status"
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"], ["telemetry_readings.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reading_id",
            "model_id",
            "model_version",
            "parameter_version",
            name="uq_analytics_result_identity",
        ),
    )
    op.create_table(
        "analytics_streams",
        sa.Column("asset_id", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("run_key", sa.String(length=100), nullable=False),
        sa.Column("watermark_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watermark_reading_id", sa.BigInteger(), nullable=True),
        sa.Column("last_identity", sa.String(length=400), nullable=True),
        sa.Column("active_token", sa.Uuid(), nullable=True),
        sa.Column("active_job_id", sa.BigInteger(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("advances", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["active_job_id"], ["telemetry_processing_jobs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["watermark_reading_id"], ["telemetry_readings.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("asset_id", "source", "run_key"),
    )
    op.create_table(
        "analytics_states",
        sa.Column("asset_id", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("run_key", sa.String(length=100), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("configuration_version", sa.Integer(), nullable=False),
        sa.Column("parameter_version", sa.String(length=100), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("advances", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id", "configuration_version"],
            ["asset_configurations.asset_id", "asset_configurations.version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id", "source", "run_key"],
            [
                "analytics_streams.asset_id",
                "analytics_streams.source",
                "analytics_streams.run_key",
            ],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "asset_id",
            "source",
            "run_key",
            "model_id",
            "model_version",
            "configuration_version",
            "parameter_version",
        ),
    )
    op.add_column(
        "telemetry_processing_jobs",
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "telemetry_processing_jobs", sa.Column("claim_token", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "telemetry_processing_jobs",
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "telemetry_processing_jobs",
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "telemetry_processing_jobs",
        sa.Column("last_error", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "telemetry_processing_jobs",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint(
        "ck_telemetry_job_pending", "telemetry_processing_jobs", type_="check"
    )
    op.create_check_constraint(
        "ck_telemetry_job_status",
        "telemetry_processing_jobs",
        "status IN ('pending', 'processing', 'retry', 'completed', 'unavailable', 'failed')",
    )
    op.create_check_constraint(
        "ck_telemetry_job_attempts", "telemetry_processing_jobs", "attempts >= 0"
    )

    op.create_index(
        "ix_processing_jobs_claim",
        "telemetry_processing_jobs",
        ["status", "available_at", "lease_until"],
    )


def downgrade() -> None:
    # Refuse to erase durable analytical evidence or processing attempts.
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM analytics_results) OR
           EXISTS (SELECT 1 FROM analytics_states) OR
           EXISTS (SELECT 1 FROM analytics_streams) OR
           EXISTS (SELECT 1 FROM telemetry_processing_jobs WHERE status <> 'pending' OR attempts <> 0)
        THEN RAISE EXCEPTION 'Worker history exists; preserve it and roll back application only';
        END IF;
    END $$""")
    op.drop_constraint(
        "ck_telemetry_job_status", "telemetry_processing_jobs", type_="check"
    )
    op.drop_constraint(
        "ck_telemetry_job_attempts", "telemetry_processing_jobs", type_="check"
    )
    op.create_check_constraint(
        "ck_telemetry_job_pending", "telemetry_processing_jobs", "status = 'pending'"
    )
    op.drop_index("ix_processing_jobs_claim", table_name="telemetry_processing_jobs")
    op.drop_column("telemetry_processing_jobs", "completed_at")
    op.drop_column("telemetry_processing_jobs", "last_error")
    op.drop_column("telemetry_processing_jobs", "available_at")
    op.drop_column("telemetry_processing_jobs", "lease_until")
    op.drop_column("telemetry_processing_jobs", "claim_token")
    op.drop_column("telemetry_processing_jobs", "attempts")
    op.drop_table("analytics_states")
    op.drop_table("analytics_streams")
    op.drop_table("analytics_results")
    # ### end Alembic commands ###
