// Real installed Chrome + real isolated API. No injected responses or credentials in evidence.
const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');const assert=require('node:assert/strict');
const {chromium}=require('../data/generated/single-transformer/tooling/node_modules/playwright');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'data/generated/single-transformer'),out=path.join(root,'docs/evidence/single-transformer-app-20261011');
const prefix=['compose','--env-file',path.join(dir,'private.env'),'-f',path.join(root,'integration/compose.single-transformer.yaml')];
function docker(args){const r=cp.spawnSync('docker',[...prefix,...args],{cwd:root,encoding:'utf8',timeout:90000});assert.equal(r.status,0,'Owned Docker operation failed: '+args.slice(0,4).join(' '));return r.stdout;}
const config=JSON.parse(docker(['config','--format','json']));assert.match(config.name,/^powernxt_single_/);assert.equal(config.services.db.environment.POSTGRES_DB,'single_transformer_app_test');
const base='http://127.0.0.1:'+config.services.backend.ports[0].published,ui='http://127.0.0.1:'+config.services.frontend.ports[0].published;
const seed=JSON.parse(fs.readFileSync(path.join(dir,'seed.json'))),token=fs.readFileSync(path.join(dir,'private/operator.txt'),'utf8').trim(),reader=fs.readFileSync(path.join(dir,'private/reader.txt'),'utf8').trim();
const report={timestamp:new Date().toISOString(),project:config.name,ui,api:base,asset_id:seed.asset_id,source:seed.source,run_id:seed.run_id,configuration:1,checks:[],requests:[],page_errors:[],actual_api:true,fixture_responses:false};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){const deadline=Date.now()+25000;while(Date.now()<deadline){if(await fn())return;await delay(100);}throw Error(label);}
async function api(route,payload,credential=token){const r=await fetch(base+route,{method:payload?'POST':'GET',headers:{Authorization:'Bearer '+credential,'Content-Type':'application/json','Connection':'close'},body:payload?JSON.stringify(payload):undefined,signal:AbortSignal.timeout(15000)});assert.ok(r.ok,route+' -> '+r.status);return r.json();}
function snapshot(name){docker(['exec','-T','backend','python','-m','integration.snapshot_single_transformer','--output','/evidence/'+name+'.json']);return JSON.parse(fs.readFileSync(path.join(dir,name+'.json')));}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});report.browser_version=browser.version();const context=await browser.newContext({viewport:{width:1600,height:1000},reducedMotion:'reduce'});const p=await context.newPage();let backendStopped=false;
p.on('pageerror',e=>report.page_errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(base))report.requests.push({method:r.request().method(),url:r.url(),status:r.status()});});
const button=name=>p.getByRole('button',{name,exact:true});const visible=async text=>{for(const item of await p.getByText(text,{exact:false}).all())if(await item.isVisible())return true;return false;};
async function nav(name){await button(name).click();await delay(400);}
async function login(credential){if(await button('Disconnect').isVisible().catch(()=>false))await button('Disconnect').click();await p.getByLabel('Operator Bearer Token').fill(credential);await button('Authenticate').click();await until(()=>button('Disconnect').isVisible(),'Authentication failed');}
async function query(){await button('Query stream incidents').click();await until(()=>button('Inspect').first().isVisible(),'Stored incidents unavailable');}
async function inspect(id){await p.locator('tr').filter({hasText:id.slice(0,8)}).getByRole('button',{name:'Inspect',exact:true}).click();await until(()=>visible('Evidence Records ('),'Stored evidence unavailable');}
const editor=id=>p.locator(`[data-task-id="${id}"]`);
async function save(id,update,message){const e=editor(id);if(update.owner!==undefined)await e.getByLabel('Assigned person').fill(update.owner);if(update.status)await e.getByLabel('Task status').selectOption(update.status);if(update.notes!==undefined)await e.getByLabel('Task notes').fill(update.notes);await e.getByRole('button',{name:'Save task update',exact:true}).click();await until(()=>e.getByText(message,{exact:false}).first().isVisible(),'Task update missing: '+message);}
try {
 await p.goto(ui);await until(()=>visible('6 records'),'Six persisted demonstration readings not loaded');assert.equal(await p.getByRole('button',{name:'Fleet overview',exact:true}).count(),0);assert.ok(await p.getByRole('combobox',{name:'Selected transformer',exact:true}).isDisabled());assert.equal(await p.getByRole('combobox',{name:'Selected transformer',exact:true}).inputValue(),seed.asset_id);assert.equal(await p.getByLabel('Telemetry source').inputValue(),seed.source);assert.equal(await p.getByLabel('Run ID',{exact:true}).inputValue(),seed.run_id);assert.ok(await p.getByTestId('focused-provenance').textContent().then(t=>t.includes(seed.asset_id)&&t.includes('stored-reading-top-oil-1.0.2')));
 for(const name of ['Condition explorer','Trends & history','Reports','Digital twin']){await nav(name);assert.ok(await p.getByTestId('focused-provenance').textContent().then(t=>t.includes(seed.asset_id)&&t.includes(seed.run_id)));}
 await p.getByRole('tab',{name:'Electrical',exact:true}).click();assert.ok(await visible('150'));await p.getByRole('tab',{name:'Thermal',exact:true}).click();assert.ok(await visible('55'));await p.getByRole('tab',{name:'Overview',exact:true}).click();
 await nav('Trends & history');const predicted=p.locator('[data-series="predicted"] path').first();const measured=p.locator('[data-series="measured"] path').first();assert.ok((await measured.getAttribute('d')).startsWith('M47,'));assert.ok(!(await predicted.getAttribute('d')).startsWith('M47,'),'Bootstrap prediction must be a chart gap');
 const records=(await api(`/api/v1/assets/${seed.asset_id}/telemetry?source=simulator&run_id=${seed.run_id}&limit=20&offset=0`)).items;assert.equal(records.length,6);const results=[];for(const record of records)results.push(await api('/api/v1/telemetry/'+record.id+'/analytics'));results.sort((a,b)=>Date.parse(a.measurement_time)-Date.parse(b.measurement_time));assert.ok(results[0].result.payload.thermal_assessment.reasons.includes('initialized_from_measurement_prediction_not_independent'));for(const r of results){assert.equal(r.configuration_version,1);assert.equal(r.asset_id,seed.asset_id);}const latest=await api(`/api/v1/assets/${seed.asset_id}/analytics/latest?source=simulator&run_id=${seed.run_id}`);assert.equal(latest.latest_completed_reading_id,6);
 await p.getByRole('button',{name:/Inspect reading 1 at/}).click();await until(()=>visible('Historical inspection'),'History inspection absent');await button('Return to latest').first().click();
 report.checks.push('All genuine monitoring screens use the fixed asset, actual electrical/thermal values, stream/config/model provenance, six joined records and bootstrap chart gap');
 let first,second;
 if(fs.existsSync(path.join(dir,'browser-tasks.json'))){
  ({first,second}=JSON.parse(fs.readFileSync(path.join(dir,'browser-tasks.json'))));
  await login(token);await nav('Alerts & incidents');assert.ok(await p.locator('.panel.backend-workflow select').first().isDisabled());await query();await inspect(seed.incident_ids[0]);
  const complete=await api('/api/v1/maintenance/tasks/'+first),cancelled=await api('/api/v1/maintenance/tasks/'+second);
  assert.equal(complete.asset_id,seed.asset_id);assert.equal(complete.alert.incident_id,seed.incident_ids[0]);assert.equal(complete.status,'completed');assert.equal(cancelled.asset_id,seed.asset_id);assert.equal(cancelled.alert.incident_id,seed.incident_ids[1]);assert.equal(cancelled.status,'cancelled');
  report.completed_task_id=first;report.cancelled_task_id=second;report.prior_lifecycle_trace='browser-lifecycle-partial.json';
  report.checks.push('Real completed/cancelled linked tasks retained and matched to the same asset/incidents; earlier actual creation/lifecycle trace retained separately');
 }else{
 await login(token);await nav('Alerts & incidents');assert.ok(await p.locator('.panel.backend-workflow select').first().isDisabled());assert.ok(await p.locator('.panel.backend-workflow select').nth(1).isDisabled());assert.equal(await p.locator('.panel.backend-workflow select').first().inputValue(),seed.asset_id);await query();await inspect(seed.incident_ids[0]);await button('Create maintenance task').click();await p.getByLabel('Task Action Title').fill('Investigate synthetic overload evidence');await button('Create incident task').click();await until(()=>p.locator('[data-task-id]').count().then(n=>n>0),'Incident task did not open');first=await p.locator('[data-task-id]').first().getAttribute('data-task-id');report.completed_task_id=first;assert.ok(await p.getByLabel('Maintenance asset',{exact:true}).isDisabled());assert.equal(await p.getByLabel('Maintenance asset',{exact:true}).inputValue(),seed.asset_id);
 await save(first,{owner:'Demonstration operator'},'Saved backend version 2');await save(first,{status:'in_progress'},'Saved backend version 3');await save(first,{status:'completed',notes:''},'notes');assert.equal((await api('/api/v1/maintenance/tasks/'+first)).status,'in_progress');await save(first,{notes:'Reviewed synthetic evidence; this completion does not imply incident recovery.'},'Saved backend version 4');const incident=await api('/api/v1/incidents/'+seed.incident_ids[0]);assert.equal(incident.condition_status,'active');assert.equal(incident.acknowledgement.status,'unacknowledged');await nav('Alerts & incidents');await query();await inspect(seed.incident_ids[0]);await button('Acknowledge incident').click();await until(()=>visible('Acknowledged ('),'Acknowledgement absent');assert.equal((await api('/api/v1/maintenance/tasks/'+first)).status,'completed');
 await query();await inspect(seed.incident_ids[1]);await button('Create maintenance task').click();await p.getByLabel('Task Action Title').fill('Review synthetic thermal evidence');await button('Create incident task').click();await until(()=>p.locator('[data-task-id]').count().then(n=>n>0),'Second incident task missing');second=await p.locator('[data-task-id]').first().getAttribute('data-task-id');report.cancelled_task_id=second;await save(second,{status:'cancelled',notes:''},'reason');await save(second,{notes:'Demonstration cancellation with preserved incident evidence.'},'Saved backend version 2');
 report.checks.push('Actual incident-linked creation, assignment/start/completion and cancellation validation; condition, acknowledgement and task status remain independent');

 fs.writeFileSync(path.join(dir,'browser-tasks.json'),JSON.stringify({first,second},null,2));
 }
 await nav('What-if analysis');assert.ok(await p.locator('.panel.backend-workflow select').first().isDisabled());const before=snapshot('what-if-before');await button('Compute What-if forecast').click();await until(()=>visible('Scenario forecast generated successfully.'),'Actual What-if did not return forecast');const stateRef=await p.getByLabel('Initial state reference (UUID)').inputValue();assert.match(stateRef,/^[0-9a-f-]{36}$/);report.state_ref=stateRef;const after=snapshot('what-if-after');for(const table of ['telemetry_readings','telemetry_processing_jobs','analytics_results','analytics_states','analytics_streams','asset_configurations'])assert.deepEqual(after.tables[table],before.tables[table]);if(report.prior_lifecycle_trace){assert.equal(after.tables.what_if_snapshots.count,before.tables.what_if_snapshots.count);assert.equal(stateRef,JSON.parse(fs.readFileSync(path.join(out,report.prior_lifecycle_trace))).state_ref);}else{assert.equal(after.tables.what_if_snapshots.count,before.tables.what_if_snapshots.count+1);}
 await button('Compute What-if forecast').click();await until(()=>visible('Scenario forecast generated successfully.'),'Replay failed');assert.equal(await p.getByLabel('Initial state reference (UUID)').inputValue(),stateRef);await p.getByLabel('Reduced thermal load (p.u.)').fill('0.8');assert.equal(await p.getByText('Captured state reference:',{exact:false}).count(),0);await button('Compute What-if forecast').click();await until(()=>visible('Scenario forecast generated successfully.'),'Changed comparison failed');
 report.checks.push('Actual backend What-if captures/reuses eligible immutable state, clears stale forecasts, and preserves all reading/job/result/worker-state/configuration hashes');
 await login(reader);await nav('Alerts & incidents');await query();await inspect(seed.incident_ids[1]);assert.ok(await button('Acknowledge incident').isDisabled());await button('Disconnect').click();await p.getByLabel('Operator Bearer Token').fill('invalid-verification-token');await button('Authenticate').click();await until(async()=>report.requests.some(r=>r.url.endsWith('/api/v1/operators/me')&&r.status===401)&&(await p.getByRole('alert').count())>0,'Real invalid-token error absent');await p.getByLabel('Operator Bearer Token').fill('');await login(token);
 report.checks.push('Actual reader mutation controls and invalid-credential HTTP401; credentials remain origin-scoped and private');
 await p.reload();await until(()=>button('Disconnect').isVisible(),'Session not restored');await nav('Maintenance');await button('Load / refresh incident-linked tasks').click();await until(()=>editor(first).isVisible(),'Persisted tasks absent');assert.ok(await editor(first).getByText('Saved: Completed',{exact:false}).isVisible());assert.ok(await editor(second).getByText('Saved: Cancelled',{exact:false}).isVisible());await p.screenshot({path:path.join(out,'chrome-maintenance.png'),fullPage:true});
 const persistBefore=snapshot('restart-before');docker(['stop','backend']);backendStopped=true;await button('Load / refresh incident-linked tasks').click();await until(()=>visible('Cannot reach the maintenance backend'),'Actual stopped-backend error absent');docker(['start','backend']);backendStopped=false;await until(async()=>{try{return(await fetch(base+'/health/ready',{headers:{Connection:'close'}})).ok;}catch{return false;}},'Backend did not restart');const persistAfter=snapshot('restart-after');assert.deepEqual(persistAfter,persistBefore);await button('Load / refresh incident-linked tasks').click();await until(()=>editor(first).isVisible(),'Restarted tasks absent');report.restart_tables=Object.keys(persistBefore.tables).length;
 report.checks.push('Real isolated API stop/restart: offline error/recovery in Chrome and exact hashes/counts across all persisted tables');
 await nav('Digital twin');await context.setOffline(true);await button('Refresh').click();await until(()=>p.getByRole('alert').count().then(n=>n>0),'Browser offline error absent');await context.setOffline(false);await button('Refresh').click();await until(()=>visible('6 records'),'Browser network recovery failed');
 await p.getByLabel('Telemetry source').selectOption('device');await until(()=>visible('This selected stream has no telemetry.'),'Empty device stream missing');await nav('What-if analysis');await button('Compute What-if forecast').click();await until(()=>visible('state_unavailable'),'Unavailable state error absent');assert.equal(await p.getByText('Captured state reference:',{exact:false}).count(),0);await p.getByLabel('Telemetry source').selectOption('simulator');await p.getByLabel('Run ID',{exact:true}).first().fill(seed.run_id);await button('Apply run').click();await nav('Digital twin');await until(()=>visible('6 records'),'Simulator stream did not recover');report.checks.push('Real browser offline recovery, empty device isolation, unavailable What-if state, and return to stored simulator records');
 await p.setViewportSize({width:390,height:844});await button('Open navigation').click();await p.getByRole('dialog').getByRole('button',{name:'Trends & history',exact:true}).click();await delay(500);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await p.screenshot({path:path.join(out,'chrome-mobile.png'),fullPage:true});await p.setViewportSize({width:1600,height:1000});await nav('Digital twin');await p.screenshot({path:path.join(out,'chrome-overview.png'),fullPage:true});await button('Switch to dark theme').click();assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');await p.screenshot({path:path.join(out,'chrome-dark.png'),fullPage:true});report.checks.push('390px responsive navigation, reduced motion and no page horizontal overflow (emulation, not a physical phone)');
 assert.deepEqual(report.page_errors,[]);report.status='PASS';console.log('PASS actual Chrome: '+report.checks.length+' workflow groups');
}catch(e){report.status='FAIL';report.failure=e.message;await p.screenshot({path:path.join(out,'chrome-failure.png'),fullPage:true}).catch(()=>{});console.error(e.message);process.exitCode=1;}finally{if(backendStopped)docker(['start','backend']);fs.writeFileSync(path.join(out,'browser-verification.json'),JSON.stringify(report,null,2)+'\n');await browser.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
